# Settings related to plugin messages
messages:
  # The prefix to use for plugin messages
  prefix: '&0[&7AlphaChest&0]'
  
  # The color to use for text for specific message types
  colors:
    info: '&f'
    success: '&2'
    warning: '&6'
    error: '&4'
    misc: '&1'

# Interval (in minutes) the plugin should save the changed chests to disk.
# Setting this to zero disables periodic saving. 
autosave: 10

# Set this to true to suppress log messages while auto-saving chests.
silentAutosave: false

# Set this to true to clear a player's chest on death if he does not have the "alphachest.keepOnDeath" permission.
clearOnDeath: false

# Set this to true to drop the contents of the player's chest on death if he does not have the "alphachest.keepOnDeath" permission.
dropOnDeath: false
